# Generated by Django 5.0.4 on 2024-04-22 17:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osd_dashboard_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(max_length=255)),
                ('license', models.CharField(max_length=100)),
                ('topics', models.JSONField()),
                ('url', models.URLField()),
                ('avatar_url', models.URLField()),
                ('commits_url', models.URLField()),
                ('stargazers_count', models.IntegerField()),
                ('latest_commit_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('latest_committer', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GithubUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('avatar_url', models.URLField()),
                ('profile_url', models.URLField()),
            ],
        ),
    ]
