# Generated by Django 4.2.11 on 2024-05-06 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osd_dashboard_app', '0003_delete_repo_rename_repo_name_githubrepo_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('commit_url', models.URLField()),
                ('last_commit_repo_name', models.CharField(max_length=255)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osd_dashboard_app.githubrepo')),
            ],
        ),
    ]
