# Generated by Django 4.2.11 on 2024-05-08 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osd_dashboard_app', '0004_contributor'),
        ('osd_dashboard_app', '0004_repocontributor_osduserprofile'),
    ]

    operations = [
    ]
