# Generated by Django 4.2.11 on 2024-05-09 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osd_dashboard_app', '0005_merge_20240508_1649'),
        ('osd_dashboard_app', '0005_merge_20240508_1758'),
    ]

    operations = [
    ]
