# Generated by Django 4.2.11 on 2024-05-30 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='githubuser',
            old_name='user_name',
            new_name='github_username',
        ),
    ]
