# Generated by Django 4.2.11 on 2024-08-15 09:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('license', models.CharField(max_length=100)),
                ('topics', models.JSONField()),
                ('url', models.URLField()),
                ('commits_url', models.URLField()),
                ('stargazers_count', models.IntegerField()),
                ('description', models.TextField(max_length=1000)),
                ('latest_commit_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('latest_committer', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='last_commit_repo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
