# Generated by Django 4.2.11 on 2024-06-07 23:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GithubRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('license', models.CharField(max_length=100)),
                ('topics', models.JSONField()),
                ('url', models.URLField()),
                ('commits_url', models.URLField()),
                ('stargazers_count', models.IntegerField()),
                ('latest_commit_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('latest_committer', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RepoContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('commit_url', models.URLField()),
                ('last_commit_repo_name', models.CharField(max_length=255)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repos_app.githubrepo')),
            ],
        ),
    ]
