# Generated by Django 5.0.4 on 2024-04-22 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repos_app', '0002_githubrepo_githubuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Repo',
        ),
        migrations.RenameField(
            model_name='githubrepo',
            old_name='repo_name',
            new_name='name',
        ),
    ]
