# Generated by Django 4.2.11 on 2024-05-08 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repos_app', '0004_contributor'),
        ('repos_app', '0004_repocontributor_osduserprofile'),
    ]

    operations = [
    ]
