# Generated by Django 4.2.11 on 2024-05-10 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repos_app', '0006_merge_20240509_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='githubrepo',
            name='avatar_url',
        ),
        migrations.DeleteModel(
            name='Contributor',
        ),
    ]
