# Generated by Django 4.2.11 on 2024-05-24 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repos_app', '0007_remove_githubrepo_avatar_url_delete_contributor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GithubUser',
        ),
        migrations.DeleteModel(
            name='OSDUserProfile',
        ),
    ]
